#!/bin/sh

INT_FILE="/tmp/mlb_score.txt"

if [ ! -f "$INT_FILE" ]; then
	echo "0" > "$INT_FILE"
fi

int=$(cat "$INT_FILE")

case $BLOCK_BUTTON in
	1) firefox sportsurge.net ;;
	3) mlb_score_pdf >/dev/null 2>&1 ;;
	6) if [ "$int" -eq 0 ]; then
		int=1
	else
		int=0
	fi
	echo "$int" > "$INT_FILE"
	;;
esac

case $int in 
	0) echo " ⚾" ;;
	1) echo " ⚾ $(mlbv --filter sea | grep -oP '\d{1,2}:\d{2}: [^│]+│[^│]+│[^│]+│' | awk -F '│' '{print $2, $3, $4}' | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2};?)?)?[mGK]//g" | sed 's/[ ]\+/ /g')" ;;
esac

